---
title: "Gov 50 Final Project"
author: "Your Name Here"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does polity score relate to the duration of a civil war in the middle east? In this study, I plan to analyze polity scores from 1990-2020 within the various countries in the middle eastern region. I hypothesize that a lower polity score is associated with a shorter period of civil war. In countries that are highly authoritarian, I assume that governments are more brutal towards their citizens, place a higher emphasis on military power, and prevent civil wars from happening in the first place or crush them swiftly. Meanwhile, I predict that countries with higher polity scores are more likely to have longer civil wars. Since countries with higher polity scores already respect democratic institutions, civil wars may be prompted by terrorist organizations that aim for authoritarianism. Using data from the Gov 50 provided civil war dataset, I will be looking towards the polity score variable and conducting a set of regressions with polity score and duration of civil war. My unit of analysis is the duration of civil war. My unit of analysis is polity score which is determined through a variety of factors that measure democracy: competitive elections, openness and transparency, political participation, checks on executive power, and political stability. Polity scores range from -10 and +10, in which -10 represents a highly authoritative regime and +10 a highly democratic one. My outcome variable is the duration of the civil war within this time range. The pattern that would support my hypothesis would be a high polity score associated with a shorter duration of war. Meanwhile, disproving my hypothesis would be a high polity score with a longer duration of war, in comparison to other wars that are being analyzed.